language: crystal
sudo: required
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libopenblas-base liblapack3 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -s /usr/lib/openblas-base/libblas.so.3 /usr/lib/libcblas.so ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -s /usr/lib/lapack/liblapack.so.3 /usr/lib/liblapack.so ; fi
matrix:
  allow_failures:
  - os: osx
